title = "ESDDescriptions"
[maps.m11_10_00_00]
328001110 = "Boss Respawn Altar"
329001110 = "Training Grounds Statue"
326001110 = "Forgotten Warrior"
[maps.m60_00_00_00]
910000000 = "Erdtree Portal"
910006000 = "Golden Seed Basin"
[maps.m00_00_00_00]
910000000 = "Erdtree Teleporter"
